spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clickerheroes
    username: admin
    password: admin
  sql:
    init:
      mode: always
      schema-locations: classpath:db/ddl.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: PostgreSQL
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
